Feat/support tenant ads
Eyevinn/test-adserver pull request #57
Opened 2021-09-24 15:59 UTC by Nfrederiksen

Added possibility to configure tenant-specific ads and creatives.
 .... The parsing of the RSS feed assumes a certain structure.

2021-09-27 09:00 UTC, birme requested changes

2021-09-27 09:07 UTC, Nfrederiksen commented on api/routes.js
> +        const tenantId = host.split('.').shift();
Alright!

2021-09-27 10:44 UTC, birme approved these changes

2021-09-28 06:36 UTC, birme commented
Just update the README with documentation on how the mRSS feed should look like and how to configure where it is placed. Then we can merge this PR.

2021-09-28 11:05 UTC, birme approved these changes

2021-09-28 11:05 UTC, merged